Dah/feature/base
rbase0218/WeGreed pull request #2
Opened 2024-09-05 11:53 UTC by daun792

2024-09-05 14:53 UTC, rbase0218 requested changes
리뷰 전달드립니다!

2024-09-05 14:53 UTC, rbase0218 commented on Assets/02 Scripts/App.cs
> +    private ViewManager _view;
ViewManager의 네임이 모호하다는 생각이 듭니다. 어떤 View인지 명시되었으면 좋겠습니다.

2024-09-05 14:53 UTC, rbase0218 commented on Assets/02 Scripts/App.cs
> +    public partial class Manager
Manager 클래스와 Data 클래스가 Partial로 선언된 이유가 있나요?

2024-09-05 14:53 UTC, rbase0218 commented on Assets/02 Scripts/App.cs
> +    public static T GetUIAs<T>() where T : MonoBehaviour
As가 붙은 메서드는 어떤 것을 의미하나요?

2024-09-05 14:53 UTC, rbase0218 commented on Assets/02 Scripts/ManagerBase.cs
> +public abstract class ManagerBase : MonoBehaviour
해당 추상 클래스가 가지는 역할이 궁금합니다.

2024-09-05 14:53 UTC, rbase0218 commented on Assets/02 Scripts/ManagerBase.cs
> +    protected static IEnumerable<FieldInfo> AppFieldInfo;
Reflection은 어떤 의도를 표현하기 위해서 사용되나요?

2024-09-05 14:53 UTC, rbase0218 commented on Assets/02 Scripts/ManagerBase.cs
> +    internal static void SetFieldValue(Type type, MonoBehaviour manager)
오..이건 메서드 로직이 멋있는데요. 이렇게 진행된다면 어떤 이점을 가지나요? 사용법은 어떻게 될까요?

2024-09-06 07:47 UTC, daun792 commented on Assets/02 Scripts/App.cs
> +    private ViewManager _view;
TitleManager나 LobbyManager처럼 한 씬의 매니징을 담당하는 매니저 클래스는 해당 씬에서만 필요하기 때문에 ViewManager를 상속해서 App에 넣어둘 생각입니다.
역할 자체만 보면 SceneManager같은 네이밍이 더 어울릴 거 같긴 한데, SceneManager보다 명확하게 전달할 수 있는 네이밍을 고민하다가 ViewManager로 넣었습니다~!!

2024-09-06 07:49 UTC, daun792 commented on Assets/02 Scripts/App.cs
> +    public partial class Manager
partial class로 선언한 이유는 해당 클래스를 여러 파일이나 코드 부분으로 나누어 관리할 수 있도록 하기 위해서 입니다! App 클래스 내에서 Manager라는 부분을 여러 파일로 나눠서 확장하거나 수정할 여지를 두기 위해 partial로 선언하였습니다~!!

2024-09-06 07:50 UTC, daun792 commented on Assets/02 Scripts/App.cs
> +    public static T GetUIAs<T>() where T : MonoBehaviour
As가 붙은 매서드는 타입캐스팅을 의미합니다. As 메서드는 특정 객체를 원하는 타입으로 변환할 때 사용되고, 보통 안전한 형 변환을 위해 as 키워드를 내부에 사용하는 형식입니다~!!

2024-09-06 07:52 UTC, daun792 commented on Assets/02 Scripts/ManagerBase.cs
> +public abstract class ManagerBase : MonoBehaviour
ManagerBase는 Manager, Data같은 클래스들이 공통으로 가져야 할 기능을 정의하고, 그 기능을 상속받아서 사용할 수 있도록 해줍니다!(이건 너무 뻔한 설명같긴 한데..) 이 코드에서 공통 기능은 SetFieldValue 메서드를 통해 각 매니저를 App 클래서 내의 필드에 등록하는 로직입니다~!!

2024-09-06 07:54 UTC, daun792 commented on Assets/02 Scripts/ManagerBase.cs
> +    protected static IEnumerable<FieldInfo> AppFieldInfo;
App 클래스의 필드들을 찾아서 매니저들을 동적으로 등록하는 기능입니다! 컴파일 시점에 타입을 알 수 없을 때 런타임에 타입을 결정하고 조작하는 기능을 제공합니다. 새로운 매니저가 추가될 때마다 코드 수정없이 자동으로 처리되는 확장성을 구현하기 위함입니다~!!

2024-09-06 07:56 UTC, daun792 commented on Assets/02 Scripts/ManagerBase.cs
> +    internal static void SetFieldValue(Type type, MonoBehaviour manager)
이점(위에서 말했지만)
1. 자동으로 매니저 등록
2. 유연한 구조
3. 코드의 재사용성
4. 유지보수 용이성

사용법
1. 매니저 클래스 생성
2. 용도에 따라 ViewManager, Manager, Data 상속
3. Awake문 내에 base.Awake();
하면 끝

2024-09-06 16:04 UTC, rbase0218 commented on Assets/02 Scripts/App.cs
> +    private ViewManager _view;
Scene의 매니징을 담당하는 매니저 클래스인거죠? 알겠습니다. 확인했습니다.

2024-09-06 16:08 UTC, rbase0218 commented on Assets/02 Scripts/App.cs
> +    public partial class Manager
제가 평소에 Partial 클래스는 용도에 따른 코드 분리를 위해서 사용하고 있어서 지금 작성하신게 어떤 의도로 사용될 지 제대로 감이 잡히지가 않네요. 이건 저한테 생소한 방법이니까 추후 사용을 기대하겠습니다!

2024-09-06 16:22 UTC, rbase0218 commented on Assets/02 Scripts/ManagerBase.cs
> +public abstract class ManagerBase : MonoBehaviour
이전에 FieldInfo를 사용하다가 List나 Generic 타입의 경우 Add, Remove에서 고생했던 경험이 있는데, 이런 쪽으로 문제가 없을까요? 당시에는 조금..(많이) 우회해서 사용했던 기억이 나서요.

2024-09-06 16:23 UTC, rbase0218 commented on Assets/02 Scripts/ManagerBase.cs
> +    protected static IEnumerable<FieldInfo> AppFieldInfo;
짱입니다. 요건 윗 리뷰로 대체하겠습니다.

2024-09-06 16:24 UTC, rbase0218 commented on Assets/02 Scripts/ManagerBase.cs
> +    internal static void SetFieldValue(Type type, MonoBehaviour manager)
이 부분은 정말 신기하네요. 구현 동작이 궁금해집니다. 확인했습니다!

2024-09-06 16:33 UTC, merged