Feat : 스탯값 인스펙터에서 수정할 수 있도록 수정
rbase0218/WeGreed pull request #5
Opened 2024-09-09 08:10 UTC by daun792

![zoqcu](https://github.com/user-attachments/assets/540a2d8e-356d-475a-982d-1f4f7be69b23)
- UnitStatus 스크립트에 StatusCount 리스트 추가
- StatusCount 내의 _currentValue 직렬화
- 어떤 데이터의 값인지 헷갈려서 열거형인 StatusType형 변수도 추가함

2024-09-09 09:43 UTC, rbase0218 requested changes
리뷰 전달드립니다!

2024-09-09 09:43 UTC, rbase0218 commented on Assets/02 Scripts/Contents/Status/UnitStatus.cs
>  public class UnitStatus : ScriptableObject
UnitStatus에서 Status를 수정하기 위한 접근 프로세스가 어떻게 될까요?

2024-09-09 09:43 UTC, rbase0218 commented on Assets/02 Scripts/Contents/Status/StatusCount.cs
> -    public float Value => _currentValue;
[Field: SerializeField] 어트리뷰트를 적용해보면 좋을 것 같습니다.

2024-09-09 09:52 UTC, rbase0218 requested changes
리뷰를 조금 추가해서 다시 전달드려요~

2024-09-09 09:52 UTC, rbase0218 commented on Assets/02 Scripts/Contents/Status/UnitStatus.cs
> +    [SerializeField] private List<StatusCount> StatusList;
List<StatusCount>를 Wrap해서 StatusCount를 책임지는 LIst를 만드는 것도 좋아보입니다.

2024-09-09 09:52 UTC, rbase0218 commented on Assets/02 Scripts/Contents/Status/UnitStatus.cs
>      public StatusCount GetStatus(StatusType type)
찾는 StatusType이 없을 때, Return에서 New를 하지 않고 내부적으로 Null 용도의 값을 가지고 있으면 공간적 효율을 올릴 수 있을 것 같아요.

2024-09-13 11:28 UTC, daun792 commented on Assets/02 Scripts/Contents/Status/UnitStatus.cs
>      public StatusCount GetStatus(StatusType type)
좋은 생각이에요

2024-09-13 11:42 UTC, daun792 commented on Assets/02 Scripts/Contents/Status/StatusCount.cs
> -    public float Value => _currentValue;
제가 검색해봤는데요, [field:SerializeField]는 프로퍼티도 인스펙터에 띄울 수 있는 [SerializeField]라고 이해가 되어서요.
병현님께서 말씀하신 'Private으로 잠글 수 없지만, 직렬화나 해당 필드가 속한 클래스에서만 수정할 수 있도록 Field: SerializeField를 사용할 수 있습니다.'는 [SerializeField]도 되는 기능 아닌가요?
굳이 [field:SerializeField]로 수정해야 할 이유를 찾지 못했습니다.
제가 잘못 이해한거라면 말씀해 주세요ㅠ

그리고 말씀해주신 [field:SerializeField]를 활용할 수 있나 살펴봤는데, set이 블록으로 되어있는 프로퍼티는 사용이 불가하다고 하네요.
그래서 지금 한 것처럼
[SerializeField] private float _currentValue;

    public float Value
    {
        get => _currentValue;

        set
        {
            _currentValue = Mathf.Clamp(value, _data.MinValue, _data.MaxValue);

            OnValueChanged?.Invoke(_currentValue);
        }
    }
이렇게 한 후, OnValidate 이벤트 함수를 이용하여 _currentValue값이 인스펙터창에서 변경됐을 시 Value의 set 블록 부분을 실행시켜 주는게 최선 같아 보입니다.

2024-09-13 11:44 UTC, daun792 commented on Assets/02 Scripts/Contents/Status/UnitStatus.cs
>  public class UnitStatus : ScriptableObject
HP를 수정한다고 가정할 경우,
- UnitStatus.GetStatus(StatusType.HP).AddValue(10);
- UnitStatus.GetStatus(StatusType.HP).Value = 10;
이런 식으로 접근하면 됩니다.

현재 HP값을 가져온다고 가정할 경우,
- var currHP = UnitStatus.GetStatus(StatusType.HP).Value;
이런 식으로 접근하면 되겠네요.

2024-09-13 11:47 UTC, daun792 commented on Assets/02 Scripts/Contents/Status/UnitStatus.cs
> +    [SerializeField] private List<StatusCount> StatusList;
선생님 List를 Wrap한다는 게 어떤 의미인지 모르겠습니다.
List를 감싸는 클래스를 만드는 방법이라고 이해했는데 맞나요?
맞다면 그래야 하는 이유를 잘 모르겠습니다,,
이미 이 List는 StatusCount를 추가하고 삭제하는 용도가 아닌, 각각의 StatusCount 내부의 currentValue값을 수정하기 위한 용도가 아닌가요?
어떤 의미로 말씀하신 건가요??

2024-09-13 12:19 UTC, closed without merging

2024-09-13 14:41 UTC, rbase0218 reviewed
와 리뷰 작성하고 Submit을 안했네요

2024-09-13 14:41 UTC, rbase0218 commented on Assets/02 Scripts/Contents/Status/UnitStatus.cs
>  public class UnitStatus : ScriptableObject
다은님께서 해당 코드를 작성하시면서 많은 고민을 해보셨으리라 생각합니다. 저같은 경우에는 쉽게 놓치는 부분들이 있어서, 이 질문은 제안 차원에서 작성드리려고 처음에 남겼습니다!

#### 1) `UnitStatus.GetStatus(StatusType.HP).AddValue(10);`
#### 2) `UnitStatus.GetStatus(StatusType.HP).Value = 10;`

두 방식으로 접근 가능하다고 할 때, 왜 두 방식을 채택하셨는지 생각 해보시는 것을 추천드립니다.
왜? 사칙연산을 수행하는 메서드만 사용하지 않고 프로퍼티를 추가했는지?와 같은 고민들이 도움이 되리라 생각합니다.

2024-09-13 14:41 UTC, rbase0218 commented on Assets/02 Scripts/Contents/Status/UnitStatus.cs
>  public class UnitStatus : ScriptableObject
참고로 덧붙이자면 저도 Status 시스템 구현할 때 이렇게 했어요!

2024-09-13 14:41 UTC, rbase0218 commented on Assets/02 Scripts/Contents/Status/UnitStatus.cs
> +    [SerializeField] private List<StatusCount> StatusList;
일단 추가 답변을 드리기 전에 제가 이해하고 있는 전제를 말씀드릴게요! 현재 `UnitStatus` 클래스는 `StatusCount`와 `StatusCount`의 계산은 진행되지만, `UnitStatus`와 `UnitStatus` 사이의 계산은 지금 불가능한 것으로 알고 있어요! 
제가.... 지금 GitHub로 코드를 봐서 놓치는 부분이 있을 수 있어요. 만약 아니라면 해당 코멘트는 무시해주세요!

1. `List<StatusCount>`와 `List<StatusCount>`간의 연산도 분명 필요할 일이 있을 것 같습니다.
- 2개의 `Status`에 영향이 있을 때, 단순히 메서드를 2번 호출하는 것 보다 하나의 메서드에서 처리할 수 있다면 좋을 것 같아요.

2. 그러면 `List<StatusCount>`를 연산해주는 메서드를 `UnitStatus`에서 만들 수도 있습니다. 하지만 객체의 역할을 분산시키는 것도 좋을 것 같습니다!

지금 다시 보니까 처음 코멘트가 너무 추상적이었네요...^^; 쏴리

2024-09-13 14:41 UTC, rbase0218 commented on Assets/02 Scripts/Contents/Status/StatusCount.cs
> -    public float Value => _currentValue;
정정하겠습니다! 인스펙터로 노출할 수 없는 코드네요. 제가 잘못 확인했습니다!!!!!

2024-09-13 14:43 UTC, daun792 commented on Assets/02 Scripts/Contents/Status/UnitStatus.cs
>  public class UnitStatus : ScriptableObject
오호............................................................................................................................................................... 알겠습니다

2024-09-13 14:44 UTC, daun792 commented on Assets/02 Scripts/Contents/Status/UnitStatus.cs
> +    [SerializeField] private List<StatusCount> StatusList;
오호 ㅋ 좋은 지적이네요. 감사합니다. 연휴 끝나고 건들여볼게요